[target.aarch64-linux-android]
linker = "C:/Users/Logeshwar Manivannan/AppData/Local/Android/Sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/windows-x86_64/bin/aarch64-linux-android22-clang++.cmd"

[target.armv7-linux-androideabi]
linker = "C:/Users/Logeshwar Manivannan/AppData/Local/Android/Sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/windows-x86_64/bin/armv7a-linux-androideabi22-clang++.cmd"

[target.i686-linux-android]
linker = "C:/Users/Logeshwar Manivannan/AppData/Local/Android/Sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/windows-x86_64/bin/i686-linux-android22-clang++.cmd"

[target.x86_64-linux-android]
linker = "C:/Users/Logeshwar Manivannan/AppData/Local/Android/Sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/windows-x86_64/bin/x86_64-linux-android22-clang++.cmd"
